In [1]:
import numpy as np
list = [1,2,3,4,5]
print(list)

[1, 2, 3, 4, 5]


In [2]:
print (' 1D Array')
a= np.array ( [1,2,3,4])
print (a)
###
b= np.array ( [[ 1,2,3],
               [2,4,5,]])

print('2D Array',b)
###
print ( '3D Array')
c= np.array ([[[1,2,3,4],
               [11,55,4,4],
               [7,88,77,77]]])
print (c)

 1D Array
[1 2 3 4]
2D Array [[1 2 3]
 [2 4 5]]
3D Array
[[[ 1  2  3  4]
  [11 55  4  4]
  [ 7 88 77 77]]]


In [3]:
print(a.size)
print(b.size)
print(c.size)


4
6
12


In [4]:
print(a.shape)
print(b.shape)
print(c.shape)

(4,)
(2, 3)
(1, 3, 4)


In [5]:
x= np.array ([[11,200.2,56454.5,4],
              [44,55,2.2,100.1]])
print(x.dtype)

float64


In [6]:
#Task Assigned for Week 2 Day 2
a= np.array([[1,2,33,44],
             [44,44,5.5,100]])
print (a.T) 

[[  1.   44. ]
 [  2.   44. ]
 [ 33.    5.5]
 [ 44.  100. ]]


In [7]:
x= np.array([[1,2,3],
             [44,5,60.5]])
print(x+b)

[[ 2.   4.   6. ]
 [46.   9.  65.5]]
